version: "3.7"
services:
  mongodb_dev:
    image: mongo:latest
    container_name: mongodb_dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/dump-db:/data/dump-db
      - ./mongo/restore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    networks:
      -   api_server_default
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  gaugemeter_bck:
    image: kathemica/gaugemeter_bck:1.0.2
    hostname: node-backend
    container_name: node-backend
    restart: always
    volumes:
      - ./certs:/usr/app/certs
    environment:
      - SERVER_FINGERKEY= SET YOUR RAMDON FINGERKEY HERE
      - SENDGRID_API_KEY= SET YOUR API KEY HERE
      - JWT_SECRET= WRITE A RANDOM STRING HERE
      - CA_TOKEN_MONGO= WRITE YOUR CA.cert PASSWORD HERE
      - MONGO_URL= INSERT YOUR MONGO_URL HERE
      - MAIL_OWNER= NAME A MAIL_OWNER HERE
      - MAIL_USERNAME= SENDGRID USERNAME HERE
      - MAIL_FROM= SENDGRID MAIL FROM HERE
      - IS_TLS_MONGO= Should I connect with mongodb as TLS?
      - DB_NAME=INSERT YOUR DATABASE NAME HERE
      - isHTTPS=Will I to connect with HTTPS?
    ports:
      - 8051:8051
      - 443:443
    networks:
      - api_server_default
    command: node ./src/main/server/server.js
    depends_on:
      - mongodb_dev
networks:
  api_server_default:
    driver: bridge
